### ISSUE TITLE
"Access was denied. You may have entered your credentials incorrectly, or you might not have access to the requested resource or operation."

### ISSUE THREAD

**Issue by ondrovic** [TA-Geoforce/react-leaflet-bing-v2#21]
Regardless on the Bing API Key provided the error message I get is, have created a couple different keys with no luck

"Access was denied. You may have entered your credentials incorrectly, or you might not have access to the requested resource or operation."

**Comment by ondrovic** [comment]
This seems to have resolved itself not sure maybe my key was in a pending state

**Comment by GautamPatil1** [comment]
How much time did it take btw?


> This seems to have resolved itself not sure maybe my key was in a pending state
