### ISSUE TITLE
please document correct import of this library

### ISSUE THREAD

**Issue by barbalex** [TA-Geoforce/react-leaflet-bing-v2#4]
The readme shows:
```js
import {BingLayer} from '../src'
```

This is obviously not going to work for users.

This might not be a big problem as long as

```js
import { BingLayer } from 'react-leaflet-bing-v2'
```

just works. But due to https://github.com/TA-Geoforce/react-leaflet-bing-v2/issues/1 that is not the case for me. So I am wondering if I am importing the wrong way...

**Comment by tdurant72** [comment]
BingLayer is now deprecated what should we be using?

**Comment by Mylothros-Charalampos** [comment]
you are not wrong we will point this out better in the Readme thank you for pointing it out @barbalex :)
