### ISSUE TITLE
peer dependencies conflict with react@17.0.2

### ISSUE THREAD

**Issue by vhetet** [TA-Geoforce/react-leaflet-bing-v2#5]
I am trying to use `react-leaflet-bing-v2` in a react app create with create-react-app.
I use:
react-scripts 4.0.3
react 17.0.2
leaflet 1.7.1
react-leaflet 3.1.0

when I run `npm i react-leaflet-bing-v2` I get the following error:

```
npm ERR! While resolving: project-name
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-leaflet-bing-v2@5.0.1
npm ERR! node_modules/react-leaflet-bing-v2
npm ERR!   react-leaflet-bing-v2@"*" from the root project
```

Is there a reason why the peerDependencies are still on 16.8.0? Could we bump it? I tried to do it myself and it worked for the example but when importing it in my app created with `create-react-app` it still fails.

Edit: forgot to say in my original message. Thank you so much for creating `react-library-bing-v2`!

**Comment by Mylothros-Charalampos** [comment]
updated
