### ISSUE TITLE
Bing Layer Deprecated

### ISSUE THREAD

**Issue by tdurant72** [TA-Geoforce/react-leaflet-bing-v2#6]
in the current example we are importing the BingLayer, now you have src but I assume we should be doing import {BingLayer} from "react-leaflet-bing-v2; But I am getting BingLayer deprecated. Could you updated your example or give us guidance on the proper way to implement your example?
Thank you in advance

**Comment by Mylothros-Charalampos** [comment]
yes in your project you have to import { BingLayer } from 'react-leaflet-bing-v2' and it will work.
